/*Copyright (c) 2018-2019 fico.com All Rights Reserved.
 This software is the confidential and proprietary information of fico.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with fico.com*/
package com.testingleaveproject17thoct.salesdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.procedure.WMProcedureExecutor;

import com.testingleaveproject17thoct.salesdb.models.procedure.*;

@Service
public class SalesdbProcedureExecutorServiceImpl implements SalesdbProcedureExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(SalesdbProcedureExecutorServiceImpl.class);

    @Autowired
    @Qualifier("salesdbWMProcedureExecutor")
    private WMProcedureExecutor procedureExecutor;

    @Transactional(value = "salesdbTransactionManager")
    @Override
    public ProcedureCreateEmptyBlockResponse executeProcedure_CreateEmptyBlock(Integer baddr, Integer bcount) {
        Map<String, Object> params = new HashMap<>(2);

        params.put("B_ADDR", baddr);
        params.put("B_COUNT", bcount);

        return procedureExecutor.executeNamedProcedure("Procedure_CreateEmptyBlock", params, ProcedureCreateEmptyBlockResponse.class);
    }

}