/*Copyright (c) 2018-2019 fico.com All Rights Reserved.
 This software is the confidential and proprietary information of fico.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with fico.com*/
package com.testingleaveproject17thoct.salesdb.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

import com.testingleaveproject17thoct.salesdb.service.SalesdbProcedureExecutorService;
import com.testingleaveproject17thoct.salesdb.models.procedure.*;

@RestController(value = "Salesdb.ProcedureExecutionController")
@RequestMapping("/salesdb/procedureExecutor")
@Api(value = "ProcedureExecutionController", description = "controller class for procedure execution")
public class ProcedureExecutionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(ProcedureExecutionController.class);

    @Autowired
    private SalesdbProcedureExecutorService procedureService;

    @RequestMapping(value = "/procedure/execute/Procedure_CreateEmptyBlock", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Procedure_CreateEmptyBlock")
    public ProcedureCreateEmptyBlockResponse executeProcedure_CreateEmptyBlock(@RequestParam(value = "B_ADDR") Integer baddr, @RequestParam(value = "B_COUNT") Integer bcount, HttpServletRequest _request) {
        LOGGER.debug("Executing named procedure: Procedure_CreateEmptyBlock");
        ProcedureCreateEmptyBlockResponse _result = procedureService.executeProcedure_CreateEmptyBlock(baddr, bcount);
        LOGGER.debug("got the result for named procedure: Procedure_CreateEmptyBlock, result:{}", _result);
        return _result;
    }

}